
$(function () {
    $('#chatBody').hide();
    $('#loginBlock').show();
    $('#txtUserName').focus();

    //refrence on autogenerated proxy of hub
    var chat = $.connection.chatHub;

    //function that hub calls when message recieved
    chat.client.addMessage = function (name, message) {
        //adding messages on the web page
        $('#chatroom').append('<p><b>' + htmlEncode(name) + '</b>: ' + htmlEncode(message) + '</p>');
    };

    //function that calls when new user is connected
    chat.client.onConnected = function (id, userName, allUsers) {

        $('#loginBlock').hide();
        $('#chatBody').show();
        $('#message').focus();

        //setting in hidden fields current user's name and id
        $('#hdId').val(id);
        $('#username').val(userName);
        $('#header').html('<h3>Hello, ' + userName + '</h3>');

        //adding of all users
        for (i = 0; i < allUsers.length; i++) {
            AddUser(allUsers[i].ConnectionId, allUsers[i].Name);
        }
    }

    //adding a new user
    chat.client.onNewUserConnected = function (id, name) {
        AddUser(id, name);
    }

    //removing a user
    chat.client.onUserDisconnected = function (id, userName) {
        $('#' + id).remove();
    }

    //opening a connection
    $.connection.hub.start().done(function () {

        $('#sendmessage').click(function () {
            // Calling the Send hub method
            chat.server.send($('#username').val(), $('#message').val());
            $('#message').val('');
        });

        // login processing
        $("#btnLogin").click(function () {

            var name = $("#txtUserName").val();
            if (name.length > 0) {
                chat.server.connect(name);
            }
            else {
                alert("Enter you name");
            }
        });
    });
});

// Encoding tags
function htmlEncode(value) {
    var encodedValue = $('<div />').text(value).html();
    return encodedValue;
}

// Adding a new user
function AddUser(id, name) {

    var userId = $('#hdId').val();

    if (userId != id) {

        $("#chatusers").append('<p id="' + id + '"><b>' + name + '</b></p>');
    }
}
